bst<-c(1, 2, 2, 3, 3, 4, 5, 5, 6, 7)
avl<-c(1, 2, 2, 3, 3, 3, 3, 4, 4, 4)
buscas <- range(0, length(avl))
comparacoes <- range(0, avl, bst)
plot(avl, type = "l", col = "blue", ylim = comparacoes, ann=FALSE)
box()
lines(bst, type = 'l', col = 'red')
title(main = "AVL vs BST", font.main = 4)
title(ylab = "Comparacoes")
title(xlab = "Buscas")
legend(1, comparacoes[2], c("AVL", "BST"), cex = 0.8, col = c("blue", "red"), lty = 1:2)